### ISSUE TITLE
Colonists don't stop hunting when their weapon runs out of ammo

### ISSUE THREAD

**Issue by mwerezak** [NoImageAvailable/CombatRealism#13]
They just keep on going in an endless cycle of aim-then-fail-to-shoot.

Making them drop their gun while aiming causes them to frozen in an aiming state.

Workaround: make them drop their gun then draft-undraft to make them snap out of it.

1.6.0

**Comment by mwerezak** [comment]
Still happens after upgrading to 1.6.2 (same save).

**Comment by NoImageAvailable** [comment]
Fixed in upcoming build
