### ISSUE TITLE
No way to prioritize hauling of backpacks/tactical vests, colonists don't put them away

### ISSUE THREAD

**Issue by mwerezak** [NoImageAvailable/CombatRealism#14]
Backpacks and tactical vests that are dropped on the ground seem to be ignored by colonists, and no option is given in the right click menu to prioritize putting them away like there is for other items.

Workaround: draft the colonist and manually pick up the items and drop them in storage.

1.6.2

**Comment by NoImageAvailable** [comment]
Issue was already fixed in 1.6.2
