### ISSUE TITLE
Colonists run out of inventory space, flip out

### ISSUE THREAD

**Issue by mwerezak** [NoImageAvailable/CombatRealism#16]
Colonists collect lots of random raw food in their inventory that they don't appear to drop (at least from casual observation). Once they run out of space, they can do strange things. For example, when one of my colonists was fetching a meal to feed to someone who was sick, they instead became stuck repeatedly picking up and dropping the same meal over and over. I was able to work around it by opening their gear tab and forcing them to drop a few random stacks of raw meat, after which they snapped out of it and went about their business.

1.6.2 (colony was originally created with 1.6.0)

**Comment by NoImageAvailable** [comment]
Should be fixed with latest release
